#+TITLE:       外贸三年总结
#+AUTHOR:      
#+EMAIL:       ian@gentoo.home
#+DATE:        2016-04-09 Sat
#+URI:         /blog/2016/04/09/外贸三年总结
#+KEYWORDS:    化工外贸,化工,外贸,org-mode,gentoo
#+TAGS:        化工,外贸,化工外贸,中间体,工作
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

我从2012年毕业，已经整整三个年头了。今年二月底三月初的时候，打算换工作，
面试了几家，都不太成功。从中，我发现自己的职业规划出现了大问题。自己做
了点思考。

我是12年8月份加入现在的公司，做化工外贸方面的工作。公司创建于1989年，
目前在自己的细分行业非常有名，是业内多家世界500强的供应商。我从一开始
进入公司就不愁没有单子做，而且经常有客户自己找上门来，发来询盘邮件。送
上门的询盘我报了好多家，居然也做成了几个客户。
另外，公司的薪酬结构是不计算提成的。所以这两个客观条件造成了我开发客户
的主动能动性不强。说得更直白点，我开发客户的能力可以说是几乎没有。这就
是我面试心仪企业不成功的一大原因了。

那么，我这三年时间又干了些什么工作呢？

可能和许多外贸同行不同，我进入这家公司后，看到的不是开发客户的紧迫性，
而是跟单的紧迫性。
公司的业务流程是属于业务员负责接单及后面所有跟单的。前面两年
（2012.08-2014.03)，给我负责了五六家大客户，还有许多小客户。后来14年我
调到另外一个外贸小组，业务量更大。负责了欧洲6家欧洲大客户，其他小客户
我数了下，前后一共有将近20家[fn:1]。
大客户要求详细，比如托盘要用哪种，打托不能混拼等等。而小客户又会冷不丁
地冒出来，打个措手不及。但是，工厂、单证又让人很不省心。工厂像是某个产
品某种包装快用完了，都不会提前给个预警，事到临头了才通知，危险品后面还
要办理危包！[fn:2]许多事情，你不能指望沟通一遍他们就会照办，如果不紧盯
着他们的进展，会造成拖延甚至出现意外情况。公司的信息化程度很低，没有
ERP，所有的要求指令都是业务根据表格+大脑在跟的。因此，我看的一个亟待解
决的问题，不是哎呀，作为新业务员我得开发客户呀，而是这么多客户，这么多
订单，需要一个良好的工作系统进行处理。本人对编程IT其实很感兴趣。我想到
一个解决方案是使用emacs上的org-mode，根据GTD的思路来管理。各种TODO和想
法采集下来，然后再把采集的信息分成Leads, Quotation, purchase, Quality,
Sample, Shipping, WorkWiki等不同的种类。完成的TODO 归档掉，或者是整理
整理进入我的工作维基。我从网上学着写了些custom agenda的配置。每天上班
就是看生成的agenda。这样一来，我完全消除掉了拖延或者忘记处理某项事务的
焦虑心理[fn:3]。

现在回头看看，感觉我走得有点过了头。打个比方，就是为了砍柴，本想是磨把
柴刀的，结果自己从头做了把屠龙刀。本来研究org-mode用于工作，研究研究着，
就对linux起了兴趣，起初用的是opensuse，后来直接一步到位用起了Gentoo，
还是自己编译内核的。桌面环境刚开始用的是KDE，后来入了窗口管理器的大坑，
先是i3，后来转用了BSPWM，最近又转回了i3。还沉迷于用Linux来实现看起来很
酷的事情，比如用wine跑各种Gal啦，在Emacs使用mu4e收发邮件啦，为了rice
desktop换用各种残缺应用啦，学习python来炒股啦等等。
当时是津津有味地在折腾的，但是现在回头看看，不禁反问自己：何必呢？这些
业余时间，其实应该用于提升自己本职工作能力的。这真是一个非常惨痛的领悟。

回忆完过去，开始展望未来。面试不成功的另外一个不利因素是英语口语不好。
两点不利因素，对于干外贸的简直是刀刀致命。当然，我也有信心，在几个月时
间内，对这两点做好完善。因为我有一整完整的自学流程[fn:4]，效果可以。可
惜，需要时间！时间！时间！

* Footnotes
[fn:4] 高考完毕自学了日语，大学里面考出了一级。我从中总结提炼了自学的
心得。
[fn:3] 正好写作的前一天发生的一件事可以做为佐证。部门经理要求查2015年8
月份的样品费用情况。其实我已经按要求登记在某个发票表格里面了。他只给出
了客户名称+四公斤数量。后来我用一条命令，来搜索工作记录就查出来了："grep 4
公斤 /path/to/my_orgmode_files/* -r"

[fn:2] 这种情况，后来我不得不建了台帐，再加上出货前提前询问包装剩余数
量。

[fn:1] 有些客户我们还不是直接直接面对的。我们在德国有分公司，沟通进来
其实比客户更累。
